import test from 'node:test';
import assert from 'node:assert/strict';
import {COLORS,DICE,createGame,step,move,region,placementError,legalPlacements,roll,paint,botAction,scores} from '../shared/game.js';
const crew=n=>Array.from({length:n},(_,i)=>({id:String(i),name:'工人'+i,color:COLORS[i].id}));
const seeded=s=>()=>((s=(s*1664525+1013904223)>>>0)/4294967296);
test('2 / 3 / 4 players receive independent pieces and only their chosen paint color',()=>{for(const n of [2,3,4]){const g=createGame(crew(n));assert.equal(g.players.length,n);for(const p of g.players){assert.equal(p.cash,30);assert.equal(p.deck.length,n===2?24:n===3?15:12);}assert.equal(new Set(g.players.flatMap(p=>p.colors)).size,n);assert.equal(new Set(g.players.map(p=>p.pawn)).size,n);assert.equal(new Set(g.players.map(p=>p.pawn.x+','+p.pawn.y)).size,n);assert.equal('pawn' in g,false);for(const p of g.players){assert.deepEqual(p.colors,[p.color]);assert.ok(p.deck.every(c=>c===p.color));}}});
test('weighted die and all edge exits remain in bounds and reverse consistently',()=>{assert.deepEqual(DICE,[1,2,2,3,3,4]);for(let y=0;y<7;y++)for(let x=0;x<7;x++)for(let dir=0;dir<4;dir++){const p=step({x,y,dir});assert.ok(p.x>=0&&p.x<7&&p.y>=0&&p.y<7);const back=step({...p,dir:(p.dir+2)%4});assert.deepEqual(back,{x,y,dir:(dir+2)%4});}assert.deepEqual(move({x:2,y:0,dir:0},2).pawn,{x:1,y:1,dir:2});assert.deepEqual(step({x:0,y:0,dir:0}),{x:0,y:0,dir:1});});
test('paint must form a domino adjacent to own worker and cannot cover one complete opponent tile',()=>{const g=createGame(crew(3));g.players[0].pawn={x:3,y:3,dir:0};g.players[1].pawn={x:6,y:6,dir:0};g.players[2].pawn={x:6,y:0,dir:0};assert.equal(placementError(g,17,18),null);assert.ok(placementError(g,0,1));assert.ok(placementError(g,23,24));assert.ok(placementError(g,6,7));g.board[17]=g.board[18]={owner:'1',color:'teal',tile:2};assert.ok(placementError(g,17,18));g.board[18]={owner:'2',color:'gold',tile:3};assert.equal(placementError(g,17,18),null);g.board[17]=g.board[18]={owner:'0',color:'coral',tile:4};assert.equal(placementError(g,17,18),null);});
test('regions use same color and orthogonal connections, not diagonals or different colors',()=>{const g=createGame(crew(2));for(const i of [0,1,8,9,16])g.board[i]={color:'teal',owner:'1',tile:i};g.board[24]={color:'teal',owner:'1',tile:24};g.board[2]={color:'blue',owner:'1',tile:2};assert.equal(region(g.board,0).length,5);assert.equal(region(g.board,24).length,1);assert.equal(region(g.board,2).length,1);});
test('payment transfers cash, stops at available funds, eliminates and neutralizes',()=>{const g=createGame(crew(3));g.players[0].pawn={x:3,y:3,dir:0};g.players[0].cash=2;for(const i of [17,16,15])g.board[i]={color:'teal',owner:'1',tile:i};roll(g,'0',0,()=>0);assert.equal(g.players[0].cash,0);assert.equal(g.players[1].cash,32);assert.equal(g.players[0].eliminated,true);assert.equal(g.phase,'direction');assert.equal(g.turn,1);assert.equal(g.lastMove.payment.due,3);assert.match(g.logs.join(' '),/付給 工人1 2 元/);g.players[1].pawn={x:3,y:2,dir:0};g.board[10]={color:'coral',owner:'0',tile:40};roll(g,'1',0,()=>0);assert.equal(g.players[1].cash,32);assert.equal(g.lastMove.payment,null);});
test('out-of-turn actions, reverse direction, and repeated paint are rejected',()=>{const g=createGame(crew(3));assert.throws(()=>roll(g,'1',0));assert.throws(()=>roll(g,'0',2));roll(g,'0',0,()=>0);assert.throws(()=>roll(g,'0',0));const pair=legalPlacements(g)[0];paint(g,'0',...pair);assert.throws(()=>paint(g,'0',...pair));});
test('360 seeded complete games preserve money and terminate with exact scoring',()=>{for(let seed=1;seed<=120;seed++)for(const n of [2,3,4]){const rng=seeded(seed),g=createGame(crew(n),rng);let turns=0;while(g.phase!=='finished'&&turns<150){const id=g.players[g.turn].id;const a=botAction(g,rng);if(a.type==='roll')roll(g,id,a.turn,rng);else paint(g,id,...a.cells);assert.equal(g.players.reduce((sum,p)=>sum+p.cash,0),30*n);assert.ok(g.players.every(p=>p.cash>=0));assert.ok(g.board.filter(Boolean).every(c=>g.players.find(p=>p.id===c.owner).color===c.color));turns++;}assert.equal(g.phase,'finished',`seed ${seed}, ${n} players`);assert.ok(g.result.winners.length);for(const p of scores(g)){assert.equal(p.total,p.cash+g.board.filter(c=>c?.owner===p.id).length);}assert.ok(g.board.filter(Boolean).length<=49);}});

test('each turn starts from that players retained position and direction',()=>{
 const g=createGame(crew(2)),start=structuredClone(g.players.map(p=>p.pawn));
 roll(g,'0',-1,()=>0);
 assert.deepEqual(g.players[0].pawn,{x:4,y:2,dir:1});
 assert.deepEqual(g.players[1].pawn,start[1]);
 const first=structuredClone(g.players[0].pawn);
 paint(g,'0',...legalPlacements(g)[0]);
 roll(g,'1',0,()=>0);
 assert.deepEqual(g.lastMove.start,start[1]);
 assert.deepEqual(g.players[0].pawn,first);
 paint(g,'1',...legalPlacements(g)[0]);
 roll(g,'0',0,()=>0);
 assert.deepEqual(g.lastMove.start,first);
 assert.deepEqual(g.players[0].pawn,{x:5,y:2,dir:1});
});
test('pieces can share a cell, retain identities, and all occupied cells reject paint',()=>{
 const g=createGame(crew(2));
 g.players[1].pawn={x:3,y:3,dir:1};
 roll(g,'0',0,()=>0);
 assert.deepEqual(g.players[0].pawn,{x:3,y:3,dir:2});
 assert.deepEqual(g.players[1].pawn,{x:3,y:3,dir:1});
 assert.match(placementError(g,24,25),/工人/);
 g.players[1].pawn={x:3,y:2,dir:1};
 assert.match(placementError(g,17,18),/工人/);
 g.players[1].eliminated=true;
 assert.equal(placementError(g,17,18),null);
});
